### ISSUE TITLE
kubectl/helm Error: forwarding ports

### ISSUE THREAD

**Issue by MBalazs90** [nightmareze1/eks-terraform#1]
Hi @nightmareze1,

I have a problem using helm with EKS. I can initialize helm, I can see tiller-deploy pod comes up with no problem, but when I try to use it, I always get the following error:

```
$ helm ls
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 10.4.6.70:10250: connect: connection refused
```
```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 10.4.5.212:10250: getsockopt: connection timed out
```

I tried to troubleshoot it but I got the same error:

```
$ kubectl -n kube-system port-forward tiller-deploy-57f988f854-9wbjs 44134
error: error upgrading connection: error dialing backend: dial tcp 10.4.6.70:10250: connect: connection refused
```
Region: eu-central-1
VPC: 10.4.0.0/16
private subnets: 

10.4.1.0/24
10.4.2.0/24
10.4.3.0/24

public subnets:

10.4.5.0/24
10.4.6.0/24
10.4.7.0/24

I made an ingress rule for 10250 on cluster/node sg but seems like no effect.

Im using eks version 1.10, same on the node side, eks-node 1.10 AMI.

Could you help me in this issue? What am I missing? Is it a SG issue from my side?

**Comment by nightmareze1** [comment]
Hello Balázs,

I Think you have a problem in SG, I recommend connect a bastion instance test the k8s instances ports with telnet or nc.

**Comment by nightmareze1** [comment]
You have a connection refused, it's a firewall/Security_group responde.
dial tcp 10.4.6.70:10250: connect: connection refused

**Comment by MBalazs90** [comment]
I know Im asking too much but can you take a look at it?
https://github.com/MBalazs90/aws-eks-cluster

**Comment by nightmareze1** [comment]
I looked your repo, I recommend separate
the bastion, workers, control plane in differents modules.
It's more easy to manage.
I think about securitys group,
you need a module to create rules is more flexible.

https://github.com/nightmareze1/eks-terraform/tree/master/modules/aws_tf_module_sg

https://github.com/nightmareze1/eks-terraform/blob/master/terraform.tfvars

In your first test , I recommend open the all ports and later you can closed the ports.

**Comment by MBalazs90** [comment]
thanks so much! 👍

**Comment by nightmareze1** [comment]
thanks to you Balazs! 👍 

kind regards!
